name: AutoRefereeCML
main: org.mctourney.autoreferee.AutoRefereeCML
version: 0.1
author: authorblues

depend:
  - AutoReferee

commands:
  forfeit:
    description: Vote to forfeit the current match
    usage: /<command> -yn
  softforfeit:
    description: Request a soft-forfeit
    usage: /<command>